language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"

after_success:  mvn site --settings target/travis/settings.xml

env:
  global:
    - secure: "LulQ2eLVSmZeDeqXp7k+aJ4qzYwYv/6SJkO6dKXDBOCsqjFbZA1VIdzr0dvkPP9RnInxfm+idivEBPcMeISDP0vxuJ9FpfsAOY1ZdzR7XH2kEPHjOVz4wPn2cTArSsitognr9lRYOmY3gPsKpZvcTyLHLq5wVAe/yJrlzli13Wc="
